# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: breeze.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62reeze.proto\x12\nbreezedemo\"%\n\x0f\x43ustomerRequest\x12\x12\n\nApiSession\x18\x01 \x01(\t\"=\n\x0b\x41piResponse\x12\x0f\n\x07Success\x18\x01 \x01(\t\x12\x0e\n\x06Status\x18\x02 \x01(\x05\x12\r\n\x05\x45rror\x18\x03 \x01(\t\"G\n\x0e\x43onnectRequest\x12\x0e\n\x06\x41ppKey\x18\x01 \x01(\t\x12\x11\n\tSecretKey\x18\x02 \x01(\t\x12\x12\n\nApiSession\x18\x03 \x01(\t\"\"\n\x0f\x43onnectResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9b\x01\n\tBreezeApi\x12\x42\n\x07\x43onnect\x12\x1a.breezedemo.ConnectRequest\x1a\x1b.breezedemo.ConnectResponse\x12J\n\x12GetCustomerDetails\x12\x1b.breezedemo.CustomerRequest\x1a\x17.breezedemo.ApiResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'breeze_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CUSTOMERREQUEST']._serialized_start=28
  _globals['_CUSTOMERREQUEST']._serialized_end=65
  _globals['_APIRESPONSE']._serialized_start=67
  _globals['_APIRESPONSE']._serialized_end=128
  _globals['_CONNECTREQUEST']._serialized_start=130
  _globals['_CONNECTREQUEST']._serialized_end=201
  _globals['_CONNECTRESPONSE']._serialized_start=203
  _globals['_CONNECTRESPONSE']._serialized_end=237
  _globals['_BREEZEAPI']._serialized_start=240
  _globals['_BREEZEAPI']._serialized_end=395
# @@protoc_insertion_point(module_scope)
