# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import breeze_pb2 as breeze__pb2


class BreezeApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/breezedemo.BreezeApi/Connect',
                request_serializer=breeze__pb2.ConnectRequest.SerializeToString,
                response_deserializer=breeze__pb2.ConnectResponse.FromString,
                )
        self.GetCustomerDetails = channel.unary_unary(
                '/breezedemo.BreezeApi/GetCustomerDetails',
                request_serializer=breeze__pb2.CustomerRequest.SerializeToString,
                response_deserializer=breeze__pb2.ApiResponse.FromString,
                )


class BreezeApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustomerDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BreezeApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=breeze__pb2.ConnectRequest.FromString,
                    response_serializer=breeze__pb2.ConnectResponse.SerializeToString,
            ),
            'GetCustomerDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustomerDetails,
                    request_deserializer=breeze__pb2.CustomerRequest.FromString,
                    response_serializer=breeze__pb2.ApiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'breezedemo.BreezeApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BreezeApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/breezedemo.BreezeApi/Connect',
            breeze__pb2.ConnectRequest.SerializeToString,
            breeze__pb2.ConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCustomerDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/breezedemo.BreezeApi/GetCustomerDetails',
            breeze__pb2.CustomerRequest.SerializeToString,
            breeze__pb2.ApiResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
