# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: breeze.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62reeze.proto\x12\nbreezedemo\"\x07\n\x05\x45mpty\"$\n\x11SubscribeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x13UnsubscribeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xb4\x01\n\x10GetNamesResponse\x12\x14\n\x0c\x45xchangeCode\x18\x01 \x01(\t\x12\x19\n\x11\x45xchangeStockCode\x18\x02 \x01(\t\x12\x15\n\rISecStockCode\x18\x03 \x01(\t\x12\x11\n\tISecToken\x18\x04 \x01(\t\x12\x13\n\x0b\x43ompanyName\x18\x05 \x01(\t\x12\x17\n\x0fISecTokenLevel1\x18\x06 \x01(\t\x12\x17\n\x0fISecTokenLevel2\x18\x07 \x01(\t\":\n\x0fGetNamesRequest\x12\x14\n\x0c\x45xchangeCode\x18\x01 \x01(\t\x12\x11\n\tStockCode\x18\x02 \x01(\t\"\x1e\n\x0eLiveStreamData\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\"%\n\x0f\x43ustomerRequest\x12\x12\n\nApiSession\x18\x01 \x01(\t\"=\n\x0b\x41piResponse\x12\x0f\n\x07Success\x18\x01 \x01(\t\x12\x0e\n\x06Status\x18\x02 \x01(\x05\x12\r\n\x05\x45rror\x18\x03 \x01(\t\"G\n\x0e\x43onnectRequest\x12\x0e\n\x06\x41ppKey\x18\x01 \x01(\t\x12\x11\n\tSecretKey\x18\x02 \x01(\t\x12\x12\n\nApiSession\x18\x03 \x01(\t\"\"\n\x0f\x43onnectResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8e\x04\n\tBreezeApi\x12\x42\n\x07\x43onnect\x12\x1a.breezedemo.ConnectRequest\x1a\x1b.breezedemo.ConnectResponse\x12J\n\x12GetCustomerDetails\x12\x1b.breezedemo.CustomerRequest\x1a\x17.breezedemo.ApiResponse\x12=\n\x0fGetDematHolding\x12\x11.breezedemo.Empty\x1a\x17.breezedemo.ApiResponse\x12G\n\x14GetLiveStreamingData\x12\x11.breezedemo.Empty\x1a\x1a.breezedemo.LiveStreamData0\x01\x12N\n\x1aSubscribeOrderNotification\x12\x11.breezedemo.Empty\x1a\x1d.breezedemo.SubscribeResponse\x12R\n\x1cUnsubscribeOrderNotification\x12\x11.breezedemo.Empty\x1a\x1f.breezedemo.UnsubscribeResponse\x12\x45\n\x08GetNames\x12\x1b.breezedemo.GetNamesRequest\x1a\x1c.breezedemo.GetNamesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'breeze_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_SUBSCRIBERESPONSE']._serialized_start=37
  _globals['_SUBSCRIBERESPONSE']._serialized_end=73
  _globals['_UNSUBSCRIBERESPONSE']._serialized_start=75
  _globals['_UNSUBSCRIBERESPONSE']._serialized_end=113
  _globals['_GETNAMESRESPONSE']._serialized_start=116
  _globals['_GETNAMESRESPONSE']._serialized_end=296
  _globals['_GETNAMESREQUEST']._serialized_start=298
  _globals['_GETNAMESREQUEST']._serialized_end=356
  _globals['_LIVESTREAMDATA']._serialized_start=358
  _globals['_LIVESTREAMDATA']._serialized_end=388
  _globals['_CUSTOMERREQUEST']._serialized_start=390
  _globals['_CUSTOMERREQUEST']._serialized_end=427
  _globals['_APIRESPONSE']._serialized_start=429
  _globals['_APIRESPONSE']._serialized_end=490
  _globals['_CONNECTREQUEST']._serialized_start=492
  _globals['_CONNECTREQUEST']._serialized_end=563
  _globals['_CONNECTRESPONSE']._serialized_start=565
  _globals['_CONNECTRESPONSE']._serialized_end=599
  _globals['_BREEZEAPI']._serialized_start=602
  _globals['_BREEZEAPI']._serialized_end=1128
# @@protoc_insertion_point(module_scope)
